
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Apr 18 14:54:18 EDT 2015
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int EQUALS = 5;
  public static final int LPAREN = 28;
  public static final int INT = 21;
  public static final int MINUS = 3;
  public static final int STATIC = 17;
  public static final int RPAREN = 29;
  public static final int SEMICOLON = 36;
  public static final int NOT = 8;
  public static final int AND = 6;
  public static final int COMMA = 34;
  public static final int CLASS = 9;
  public static final int PLUS = 2;
  public static final int MAIN = 13;
  public static final int IF = 23;
  public static final int THIS = 25;
  public static final int DOT = 35;
  public static final int EOF = 0;
  public static final int BOOLEAN = 22;
  public static final int RETURN = 16;
  public static final int TRUE = 26;
  public static final int NEW = 14;
  public static final int error = 1;
  public static final int LCURLY = 32;
  public static final int VOID = 19;
  public static final int LBRACK = 30;
  public static final int RCURLY = 33;
  public static final int TIMES = 4;
  public static final int ELSE = 10;
  public static final int RBRACK = 31;
  public static final int WHILE = 20;
  public static final int PUBLIC = 15;
  public static final int EXTENDS = 11;
  public static final int STRING = 18;
  public static final int FALSE = 27;
  public static final int LESS_THAN = 7;
  public static final int PRINT = 24;
  public static final int LENGTH = 12;
  public static final int IDENTIFIER = 38;
  public static final int INTEGER_LITERAL = 37;
}

